# -*- coding: utf-8 -*-
# vim: ft=yaml
#
# Set values specific to:
#   salt['config.get']('os_family') == RedHat.
#
# You just need to add the key:values for this `os_family` that differ
# from `defaults.yaml` + `<osarch>.yaml`.
#
# If you do not need to provide defaults via the `os_family` config,
# you can remove this file or provide at least an empty dict, e.g.
# values: {}
---
values:
  lookup:
    pkg_manager: yum
    repos:
      stable:
        humanname: Grafana stable
        name: grafana_stable
        baseurl: https://rpm.grafana.com
        gpgkey: https://rpm.grafana.com/gpg.key
        gpgcheck: 1
        repo_gpgcheck: 1
        sslverify: 1
        sslcacert: /etc/pki/tls/certs/ca-bundle.crt
        exclude: '"*beta*"'
      beta:
        humanname: Grafana beta
        name: grafana_beta
        baseurl: https://rpm.grafana.com
        gpgkey: https://rpm.grafana.com/gpg.key
        gpgcheck: 1
        repo_gpgcheck: 1
        sslverify: 1
        sslcacert: /etc/pki/tls/certs/ca-bundle.crt
...
