# -*- coding: utf-8 -*-
# vim: ft=yaml
#
# Set default values.
---
values:
  lookup:
    rootgroup: root
    pkg:
      name: grafana
    enablerepo:
      stable: true
    config: '/etc/grafana/grafana.ini'
    service:
      name: grafana-server
    group: grafana
    paths:
      conf: /etc/grafana
      data: /var/lib/grafana
      home: /usr/share/grafana
      log: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
      run: /run/grafana
    user: grafana
  cert:
    ca_server: null
    cn: null
    intermediate: []
    signing_cert: null
    signing_policy: null
    signing_private_key: null
  config:
    analytics:
      reporting_enabled: false
    security:
      secret_key: null
    users:
      allow_sign_up: false
  version: null
  # Just here for testing
  added_in_defaults: defaults_value
  winner: defaults
...
